sudo: required
dist: precise
addons:
  postgresql: '9.5'
services:
- postgresql
language: node_js
node_js:
- 6.10.0
cache:
  directories:
  - node_modules
before_install:
- npm prune
- psql -c 'create database test;' -U postgres
- sleep 5
install:
- npm install
env:
  global:
  - NODE_ENV: test
  - POSTGRES_USER: postgres
  - POSTGRES_PASSWORD: postgres
  - POSTGRES_HOST: localhost
  - POSTGRES_DB: test